create table preguntas(
id_pregunta numeric (5)not null,
preguntas nvarchar (100) not null,
nivel_preguntas numeric (5) not null,
id_respuesta_correcta numeric (5)not null,
)
create table respuestas (
id_respuesta numeric (5)not null,
respuestas nvarchar (100) not null,
nivel_respuestas numeric (5)not null, 
respu_correcta bit 
CONSTRAINT id_respuesta_PK PRIMARY KEY (id_respuesta)
)
insert into preguntas values 
( 1, 'Cual es la capital de Antioquia?', 1, 3),
( 2, 'cuantos puntos valen un triple en baloncesto?', 1 , 5),
( 3, 'cuanto es 12+32-20?', 1 , 10),
( 4, 'cual es la religion más profesada en colombia?', 1 , 16),
( 5, 'cual es la capita del pais de colombia?', 1 , 20),
( 6, 'cual es el sueldo minmo colombiano?', 2 , 22),
( 7, 'composición quimica del agua?', 2 , 28),
( 8, 'cuando vale un pasaje de en el metro de Medellin?', 2, 30 ),
( 9, 'Cómo se llaman los animales que tienen un esqueleto articulado?', 2, 36 ),
( 10, 'Cómo se llaman los animales que nacen de un huevo?', 2, 37 ),
( 11, 'Cómo elaboran las plantas su propio alimento?', 3 , 43),
( 12, 'Cómo se llama el triángulo que tiene 3 lados iguales?', 3, 46 ),
( 13, 'Cómo se dice en ingles "buenas tardes"?', 3, 50),
( 14, 'Qué expulsan las plantas por la noche?', 3 , 54),
( 15, 'Cómo se llama el conjunto de montañas que forman una unidad?', 3, 58 ),
( 16, 'Cómo se llama la representación plana de la tierra? ', 4 , 63),
( 17, 'Qué otras lenguas son cooficiales en España además del castellano?', 4 , 65),
( 18, 'Cuál es el río más largo del mundo?', 4, 69 ),
( 19, 'En qué año Colón descubrió América? ', 4, 74 ),
( 20, 'Quién es el autor de El Quijote?', 4, 79 ),
( 21, 'Cómo se le llama al resultado de la multiplicación?', 5, 82 ),
( 22, 'Cuántas patas tiene una araña?', 5,  87),
( 23, 'Cuál es el único mamífero que puede volar?', 5 , 90),
( 24, 'Cuál es el animal más rápido del mundo?', 5 , 95),
( 25, 'Cuál es la capital de Bulgaria?', 5, 99)

insert into respuestas values 
( 1, 'Barranquilla', 1 ,'false'),
( 2, 'Santader', 1 ,'false'),
( 3, 'Medellin', 1 ,'true'),
( 4, 'Bogota', 1 ,'false'),
( 5, '3 puntos', 1 ,'true'),
( 6, '4 putos', 1 ,'false'),
( 7, '2 puntos', 1 ,'false'),
( 8, '1 punto', 1 ,'false'),
( 9, '12', 1 ,'false'),
( 10, '24', 1 ,'true'),
( 11, '13', 1 ,'false'),
( 12, '55', 1 ,'false'),
( 13, 'budista', 1 ,'false'),
( 14, 'hinduista', 1 ,'false'),
( 15, 'musulmana', 1 ,'false'),
( 16, 'catolica', 1 ,'true'),
( 17, 'Manizales', 1 ,'false'),
( 18, 'Perreira', 1 ,'false'),
( 19, 'Medellin', 1 ,'false'),
( 20, 'Bogota', 1 ,'true'),
( 21, '1.250.000', 2 ,'false'),
( 22, '1.000.000', 2 ,'true'),
( 23, '800.000', 2 ,'false'),
( 24, '1.400.000', 2 ,'false'),
( 25, 'H', 2 ,'true'),
( 26, 'Hc', 2 ,'false'),
( 27, 'Co2', 2 ,'false'),
( 28, 'H2o', 2 ,'true'),
( 29, '7.000', 2 ,'false'),
( 30, '2.430', 2 ,'true'),
( 31, '1.300', 2 ,'false'),
( 32, '2.340', 2 ,'false'),
( 33, 'inversos', 2 ,'false'),
( 34, 'Vivíparos', 2 ,'false'),
( 35, 'Invertebrados', 2 ,'false'),
( 36, 'Vertebrados', 2 ,'true'),
( 37, 'Ovíparos', 2 ,'true'),
( 38, 'Vivíparos', 2 ,'false'),
( 39, 'fotosíntesis', 2 ,'false'),
( 40, 'Invertebrados', 2 ,'false'),
( 41, 'Co2', 3 ,'false'),
( 42, 'Ciclo del carbono', 3 ,'false'),
( 43, 'fotosíntesis', 3 ,'true'),
( 44, 'Biodegradación', 3 ,'false'),
( 45, 'Isoceles', 3 ,'false'),
( 46, 'Equilátero', 3 ,'true'),
( 47, 'Escaleno', 3 ,'false'),
( 48, 'Rectangulo', 3 ,'false'),
( 49, 'Hi', 3 ,'false'),
( 50, 'Good afternoon', 3 ,'true'),
( 51, 'yes, i do', 3 ,'false'),
( 52, 'Good evening', 3 ,'false'),
( 53, 'oxigeno', 3 ,'false'),
( 54, 'Dióxido de carbono', 3 ,'true'),
( 55, 'Dióxido de hidrogeno', 3 ,'false'),
( 56, 'Metano', 3 ,'false'),
( 57, 'Montaña', 3 ,'false'),
( 58, 'Cordillera', 3 ,'true'),
( 59, 'Paramo', 3 ,'false'),
( 60, 'llanura', 3 ,'false'),
( 61, 'hemisferio', 4 ,'false'),
( 62, 'tierra', 4 ,'false'),
( 63, 'Planisferio', 4 ,'true'),
( 64, 'terraplanismo', 4 ,'false'),
( 65, 'Catalán', 4 ,'true'),
( 66, 'Ingles', 4 ,'false'),
( 67, 'portugues', 4 ,'false'),
( 68, 'frances', 4,'false'),
( 69, 'El Amazonas', 4 ,'true'),
( 70, 'El orinoco ', 4 ,'false'),
( 71, 'El rio misisipi', 4 ,'false'),
( 72, 'El rio misuri', 4 ,'false'),
( 73, '1643', 4 ,'false'),
( 74, '1492', 4 ,'true'),
( 75, '1230', 4 ,'false'),
( 76, '974', 4 ,'false'),
( 77, 'gabriel garcia marquez', 4 ,'false'),
( 78, 'George Orwell', 4 ,'false'),
( 79, 'Miguel de Cervantes', 4 ,'true'),
( 80, 'J. K. Rowling', 4 ,'false'),
( 81, 'Exponencial', 5 ,'false'),
( 82, 'Producto', 5 ,'true'),
( 83, 'Fración', 5 ,'false'),
( 84, 'Integración', 5 ,'false'),
( 85, '4 patas', 5 ,'false'),
( 86, '6 patas', 5 ,'false'),
( 87, '8 patas', 5 ,'true'),
( 88, '10 patas', 5 ,'false'),
( 89, 'La mariposa', 5 ,'false'),
( 90, 'El murciélago', 5 ,'true'),
( 91, 'El loro', 5 ,'false'),
( 92, 'El pato', 5 ,'false'),
( 93, 'El zorro', 5 ,'false'),
( 94, 'El leon', 5 ,'false'),
( 95, 'El guepardo', 5 ,'true'),
( 96, 'El oso', 5 ,'false'),
( 97, 'Grecia', 5 ,'false'),
( 98, 'Noruega', 5 ,'false'),
( 99, 'Sofía', 5 ,'true'),
( 100,'Paris', 5 ,'false')

SELECT preguntas,respuestas FROM preguntas, respuestas WHERE id_respuesta_correcta=id_respuesta and nivel_preguntas = 1
SELECT preguntas,respuestas FROM preguntas, respuestas WHERE id_respuesta_correcta=id_respuesta and nivel_preguntas = 2
SELECT preguntas,respuestas FROM preguntas, respuestas WHERE id_respuesta_correcta=id_respuesta and nivel_preguntas = 3
SELECT preguntas,respuestas FROM preguntas, respuestas WHERE id_respuesta_correcta=id_respuesta and nivel_preguntas = 4
SELECT preguntas,respuestas FROM preguntas, respuestas WHERE id_respuesta_correcta=id_respuesta and nivel_preguntas = 5